CenturyLinkCloud/APIDocs

- Webhooks/webhooks-faq.md
Clarifying which public key and more info around signature verification...
> Signature Validation

- Networks/claim-network.md
- Networks/get-ip-address-list.md
- Networks/get-network-list.md
- Networks/get-network.md
- Networks/release-network.md
- Networks/update-network.md
Here are my suggested changes.
In addition, I believe you should update `APIDocs/Networks/get-network.md` to document the shape of the optional IP addresses that you can get back (it may just be to simply point them to `APIDocs/Networks/get-ip-address-list.md` for the data shape).
> Review feedback

- Firewall Policies/create-intra-dc-firewall-policy.md
Changed the requirements of the content properties.
> Update CreateIntraDC Rule

- Groups/get-group-horizontal-autoscale-policy.md
- Groups/get-group-scheduled-activities.md
- Groups/set-group-defaults.md
- Groups/set-group-horizontal-autoscale-policy.md
for: https://trello.com/c/vx2Ewhqz/35-document-server-groups-api-api
> added missing group APIs

- Groups/get-group-horizontal-autoscale-policy.md
- Groups/get-group-scheduled-activities.md
- Groups/set-group-defaults.md
- Groups/set-group-horizontal-autoscale-policy.md
fixed titles to reflect file names (Get, Set)
> fixed titles to reflect file names

- Servers/get-server.md
This will go out next iteration (December 15th Deployment) so we should time the change with that.
> Adding displayName description to GetServer

- Simple Backup/create-server-policies.md
> Create API doc for multi server policy creation

- Servers/create-server.md
- Servers/get-server.md
- Servers/import-server.md
- Webhooks/webhooks-faq.md
https://trello.com/c/uxfNurSs/346-sbs-removal-v2-api-changes
> Remove backup storage type (premium/standard) from docs 

- README.md
- Relational Database/create-subscription-backup-operation.md
- Relational Database/create-subscription-backup.md
- Relational Database/create-subscription-notificaiton-operation.md
- Relational Database/create-subscription-notification-operation.md
- Relational Database/create-subscription-notification.md
- Relational Database/create-subscription-operation.md
- Relational Database/create-subscription.md
- Relational Database/delete-subscription-backup.md
- Relational Database/delete-subscription-notification.md
- Relational Database/delete-subscription.md
- Relational Database/get-billing.md
- Relational Database/get-datacenters.md
- Relational Database/get-history.md
- Relational Database/get-promotion.md
- Relational Database/get-subscription-backups.md
- Relational Database/get-subscription-certificate.md
- Relational Database/get-subscription-notifications.md
- Relational Database/get-subscription.md
- Relational Database/get-subscriptions.md
- Relational Database/modify-subscription.md
- Relational Database/rdbs-overview.md
- Relational Database/update-subscription-notification.md
- index.md
Add RDBS API v1 doc and added a clarification to README.md on running the commit analyzer locally.
> Add RDBS API v1 doc

- Servers/create-server.md
- Servers/get-server.md
- Servers/import-server.md
- Webhooks/webhooks-faq.md
Reverts CenturyLinkCloud/APIDocs#64
@johanntang @marycadera FYI
> Revert "Remove backup storage type (premium/standard) from docs "

- Relational Database/create-subscription-backup-operation.md
- Relational Database/create-subscription-backup.md
- Relational Database/create-subscription-notification-operation.md
- Relational Database/create-subscription-notification.md
- Relational Database/create-subscription-operation.md
- Relational Database/create-subscription.md
- Relational Database/delete-subscription-backup.md
- Relational Database/delete-subscription-notification.md
- Relational Database/delete-subscription.md
- Relational Database/get-billing.md
- Relational Database/get-datacenters.md
- Relational Database/get-history.md
- Relational Database/get-promotion.md
- Relational Database/get-subscription-backups.md
- Relational Database/get-subscription-certificate.md
- Relational Database/get-subscription-notifications.md
- Relational Database/get-subscription.md
- Relational Database/get-subscriptions.md
- Relational Database/modify-subscription.md
- Relational Database/rdbs-overview.md
- Relational Database/update-subscription-notification.md
- index.md
Publish RDBS API v1 deployed on 25 APR 2016
> RDBS API v1 additions

- Relational Database/create-subscription.md
Changed create subscription to use new v1 syntax
> RDBS API v1 fix create subscription

- Groups/delete-group.md
Updated example for delete group to correctly reflect call.
> Updated example to correctly reflect call.

- Servers/get-server.md
Added isManagedOS to Server Entity for Get Server V2 API.
> Added isManagedOS to Server Entity

- Webhooks/add-webhook-targetUri.md
- Webhooks/delete-webhook-targetUri.md
- Webhooks/delete-webhook.md
- Webhooks/get-webhooks.md
- Webhooks/set-webhook.md
@turanuk Could you give this a quick review?
> Add documentation for the webhook APIs

- Servers/get-server.md
@srveit or @jim-phillips Please review and merge.
https://trello.com/c/CsEpw9Dz
Closes Issue #1634 on PublicPlatform
> Add isManagedBackup to the Get Server entities

- CAM Platform/organizations-api.md
updated error codes in api doc
> [CAM-4358] Improve KB article with error codes, detailed description, causes and solution

- Simple Backup/get-csv-restore-jobs-report.md
- Simple Backup/get-csv-restore-points-report.md
- Simple Backup/get-csv-summary-report.md
Adding documentation for SBS API endpoints introduced to production on June 29, 2018
> Sbs csv reports api docs

- Instances/make-managed-os.md
> Fix make-managed-os example and add content

- Servers/create-server.md
https://ctliotest.atlassian.net/browse/PE-1451
> [API] Remove Hyperscale references

- Examples/deploy-a-box.md
@julio-castanar, @gsanchezu 
Please review my PR
> [CAM-8437] Review and update Examples > Deploy a Box API documentation

- Simple Backup/get-datacenter-list.md
https://ctliotest.atlassian.net/browse/PE-1594
> [CTL] Removing references to UT1 from API Docs

- CAM Platform/api-cost-centers.md
@gsanchezu 
Please, review this pull rquest
> [CAM-8439] - Document CAM CostCenters API endpoints

- Application Lifecycle Management/api-boxes.md
@gsanchezu, @julio-castanar Guys, could you review this pull request, please?
> [CAM-8435]-Review and update Boxes-API-Documentation.

- Application Lifecycle Management/instances-api.md
@gsanchezu @julio-castanar 
Review this pull request.
> [CAM-8436]-Update-Instance-APIDoc

- Application Lifecycle Management/instances-api.md
> [CAM-11243] Update CAM-ALM API documentation to include abort instance operation

- Examples/deploy-a-box.md
> Clarify required parameters

- Application Lifecycle Management/api-boxes.md
- Application Lifecycle Management/instances-api.md
- CAM Platform/workspaces.md
> Changes to cam files - Matt Riddle
